// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.ProfileBulkImportJobs.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "lists")]
        #pragma warning disable CS1591
        Lists,
        #pragma warning restore CS1591
    }
}
