// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Api.CatalogItems.Item.Variants
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "-created")]
        #pragma warning disable CS1591
        Minus_created,
        #pragma warning restore CS1591
    }
}
