// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.TrackingSettings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetFieldsTrackingSettingQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "auto_add_parameters")]
        #pragma warning disable CS1591
        Auto_add_parameters,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source")]
        #pragma warning disable CS1591
        Utm_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.flow")]
        #pragma warning disable CS1591
        Utm_sourceFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.flow.type")]
        #pragma warning disable CS1591
        Utm_sourceFlowType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.flow.value")]
        #pragma warning disable CS1591
        Utm_sourceFlowValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.campaign")]
        #pragma warning disable CS1591
        Utm_sourceCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.campaign.type")]
        #pragma warning disable CS1591
        Utm_sourceCampaignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_source.campaign.value")]
        #pragma warning disable CS1591
        Utm_sourceCampaignValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium")]
        #pragma warning disable CS1591
        Utm_medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.flow")]
        #pragma warning disable CS1591
        Utm_mediumFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.flow.type")]
        #pragma warning disable CS1591
        Utm_mediumFlowType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.flow.value")]
        #pragma warning disable CS1591
        Utm_mediumFlowValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.campaign")]
        #pragma warning disable CS1591
        Utm_mediumCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.campaign.type")]
        #pragma warning disable CS1591
        Utm_mediumCampaignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_medium.campaign.value")]
        #pragma warning disable CS1591
        Utm_mediumCampaignValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign")]
        #pragma warning disable CS1591
        Utm_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.flow")]
        #pragma warning disable CS1591
        Utm_campaignFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.flow.type")]
        #pragma warning disable CS1591
        Utm_campaignFlowType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.flow.value")]
        #pragma warning disable CS1591
        Utm_campaignFlowValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.campaign")]
        #pragma warning disable CS1591
        Utm_campaignCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.campaign.type")]
        #pragma warning disable CS1591
        Utm_campaignCampaignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_campaign.campaign.value")]
        #pragma warning disable CS1591
        Utm_campaignCampaignValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id")]
        #pragma warning disable CS1591
        Utm_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.flow")]
        #pragma warning disable CS1591
        Utm_idFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.flow.type")]
        #pragma warning disable CS1591
        Utm_idFlowType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.flow.value")]
        #pragma warning disable CS1591
        Utm_idFlowValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.campaign")]
        #pragma warning disable CS1591
        Utm_idCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.campaign.type")]
        #pragma warning disable CS1591
        Utm_idCampaignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_id.campaign.value")]
        #pragma warning disable CS1591
        Utm_idCampaignValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term")]
        #pragma warning disable CS1591
        Utm_term,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.flow")]
        #pragma warning disable CS1591
        Utm_termFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.flow.type")]
        #pragma warning disable CS1591
        Utm_termFlowType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.flow.value")]
        #pragma warning disable CS1591
        Utm_termFlowValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.campaign")]
        #pragma warning disable CS1591
        Utm_termCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.campaign.type")]
        #pragma warning disable CS1591
        Utm_termCampaignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "utm_term.campaign.value")]
        #pragma warning disable CS1591
        Utm_termCampaignValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_parameters")]
        #pragma warning disable CS1591
        Custom_parameters,
        #pragma warning restore CS1591
    }
}
