// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.Flows.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "flow-actions")]
        #pragma warning disable CS1591
        FlowActions,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
    }
}
