// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.CampaignSendJobs.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetFieldsCampaignSendJobQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
    }
}
