// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.Profiles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "-created")]
        #pragma warning disable CS1591
        Minus_created,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "-email")]
        #pragma warning disable CS1591
        Minus_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "-id")]
        #pragma warning disable CS1591
        Minus_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscriptions.email.marketing.list_suppressions.timestamp")]
        #pragma warning disable CS1591
        SubscriptionsEmailMarketingList_suppressionsTimestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "-subscriptions.email.marketing.list_suppressions.timestamp")]
        #pragma warning disable CS1591
        Minus_subscriptionsEmailMarketingList_suppressionsTimestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscriptions.email.marketing.suppression.timestamp")]
        #pragma warning disable CS1591
        SubscriptionsEmailMarketingSuppressionTimestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "-subscriptions.email.marketing.suppression.timestamp")]
        #pragma warning disable CS1591
        Minus_subscriptionsEmailMarketingSuppressionTimestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "-updated")]
        #pragma warning disable CS1591
        Minus_updated,
        #pragma warning restore CS1591
    }
}
