// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.Coupons.Item.CouponCodes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsCouponCodeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unique_code")]
        #pragma warning disable CS1591
        Unique_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "expires_at")]
        #pragma warning disable CS1591
        Expires_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
    }
}
