// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.CatalogCategoryBulkUpdateJobs.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetFieldsCatalogCategoryQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "external_id")]
        #pragma warning disable CS1591
        External_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
    }
}
