// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.Reviews
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "events")]
        #pragma warning disable CS1591
        Events,
        #pragma warning restore CS1591
    }
}
