// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Back_in_stockEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "back_in_stock")]
        #pragma warning disable CS1591
        Back_in_stock,
        #pragma warning restore CS1591
    }
}
