// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Bounce_dateEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bounce_date")]
        #pragma warning disable CS1591
        Bounce_date,
        #pragma warning restore CS1591
    }
}
