// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>Font style.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ButtonBlockStyles_font_style
    {
        [EnumMember(Value = "italic")]
        #pragma warning disable CS1591
        Italic,
        #pragma warning restore CS1591
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
    }
}
