// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CampaignSendJobEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "campaign-send-job")]
        #pragma warning disable CS1591
        CampaignSendJob,
        #pragma warning restore CS1591
    }
}
