// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Carrier_deactivationEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "carrier_deactivation")]
        #pragma warning disable CS1591
        Carrier_deactivation,
        #pragma warning restore CS1591
    }
}
