// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>The integration type. Currently only &quot;$custom&quot; is supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum CatalogItemCreateQueryResourceObject_attributes_integration_type
    {
        [EnumMember(Value = "$custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
