// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum CatalogCategoryBulkCreateJobEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "catalog-category-bulk-create-job")]
        #pragma warning disable CS1591
        CatalogCategoryBulkCreateJob,
        #pragma warning restore CS1591
    }
}
