// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum CouponCodeBulkCreateJobEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "coupon-code-bulk-create-job")]
        #pragma warning disable CS1591
        CouponCodeBulkCreateJob,
        #pragma warning restore CS1591
    }
}
