// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FeaturedEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "featured")]
        #pragma warning disable CS1591
        Featured,
        #pragma warning restore CS1591
    }
}
