// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FormSeriesReportEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "form-series-report")]
        #pragma warning disable CS1591
        FormSeriesReport,
        #pragma warning restore CS1591
    }
}
