// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum FormValuesReportEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "form-values-report")]
        #pragma warning disable CS1591
        FormValuesReport,
        #pragma warning restore CS1591
    }
}
