// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum Is_double_opt_inEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "is_double_opt_in")]
        #pragma warning disable CS1591
        Is_double_opt_in,
        #pragma warning restore CS1591
    }
}
