// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>Operators for list substring filters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum ListSubstringFilter_operator
    {
        [EnumMember(Value = "contains-substring")]
        #pragma warning disable CS1591
        ContainsSubstring,
        #pragma warning restore CS1591
        [EnumMember(Value = "not-contains-substring")]
        #pragma warning disable CS1591
        NotContainsSubstring,
        #pragma warning restore CS1591
    }
}
