// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>Supported measurements for aggregation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetricAggregateQueryResourceObject_attributes_measurements
    {
        [EnumMember(Value = "count")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
        [EnumMember(Value = "sum_value")]
        #pragma warning disable CS1591
        Sum_value,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique")]
        #pragma warning disable CS1591
        Unique,
        #pragma warning restore CS1591
    }
}
