// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MobilePushMessageStandardDefinition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The channel property</summary>
        public global::Klaviyo.Models.Mobile_pushEnum? Channel { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Klaviyo.Models.MobilePushContent? Content { get; set; }
#nullable restore
#else
        public global::Klaviyo.Models.MobilePushContent Content { get; set; }
#endif
        /// <summary>The key-value pairs to be sent with the push notification</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Klaviyo.Models.MobilePushMessageStandardDefinition_kv_pairs? KvPairs { get; set; }
#nullable restore
#else
        public global::Klaviyo.Models.MobilePushMessageStandardDefinition_kv_pairs KvPairs { get; set; }
#endif
        /// <summary>The notification_type property</summary>
        public global::Klaviyo.Models.StandardEnum? NotificationType { get; set; }
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Klaviyo.Models.MobilePushOptions? Options { get; set; }
#nullable restore
#else
        public global::Klaviyo.Models.MobilePushOptions Options { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Klaviyo.Models.MobilePushMessageStandardDefinition"/> and sets the default values.
        /// </summary>
        public MobilePushMessageStandardDefinition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Klaviyo.Models.MobilePushMessageStandardDefinition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Klaviyo.Models.MobilePushMessageStandardDefinition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Klaviyo.Models.MobilePushMessageStandardDefinition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel", n => { Channel = n.GetEnumValue<global::Klaviyo.Models.Mobile_pushEnum>(); } },
                { "content", n => { Content = n.GetObjectValue<global::Klaviyo.Models.MobilePushContent>(global::Klaviyo.Models.MobilePushContent.CreateFromDiscriminatorValue); } },
                { "kv_pairs", n => { KvPairs = n.GetObjectValue<global::Klaviyo.Models.MobilePushMessageStandardDefinition_kv_pairs>(global::Klaviyo.Models.MobilePushMessageStandardDefinition_kv_pairs.CreateFromDiscriminatorValue); } },
                { "notification_type", n => { NotificationType = n.GetEnumValue<global::Klaviyo.Models.StandardEnum>(); } },
                { "options", n => { Options = n.GetObjectValue<global::Klaviyo.Models.MobilePushOptions>(global::Klaviyo.Models.MobilePushOptions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Klaviyo.Models.Mobile_pushEnum>("channel", Channel);
            writer.WriteObjectValue<global::Klaviyo.Models.MobilePushContent>("content", Content);
            writer.WriteObjectValue<global::Klaviyo.Models.MobilePushMessageStandardDefinition_kv_pairs>("kv_pairs", KvPairs);
            writer.WriteEnumValue<global::Klaviyo.Models.StandardEnum>("notification_type", NotificationType);
            writer.WriteObjectValue<global::Klaviyo.Models.MobilePushOptions>("options", Options);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
