// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchUniversalContentResponse_data_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The datetime when this universal content was created</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The definition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition? Definition { get; set; }
#nullable restore
#else
        public global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition Definition { get; set; }
#endif
        /// <summary>The name for this universal content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The status of a universal content screenshot.</summary>
        public global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes_screenshot_status? ScreenshotStatus { get; set; }
        /// <summary>The screenshot_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScreenshotUrl { get; set; }
#nullable restore
#else
        public string ScreenshotUrl { get; set; }
#endif
        /// <summary>The datetime when this universal content was updated</summary>
        public DateTimeOffset? Updated { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes"/> and sets the default values.
        /// </summary>
        public PatchUniversalContentResponse_data_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "definition", n => { Definition = n.GetObjectValue<global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition>(global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "screenshot_status", n => { ScreenshotStatus = n.GetEnumValue<global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes_screenshot_status>(); } },
                { "screenshot_url", n => { ScreenshotUrl = n.GetStringValue(); } },
                { "updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteObjectValue<global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition>("definition", Definition);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes_screenshot_status>("screenshot_status", ScreenshotStatus);
            writer.WriteStringValue("screenshot_url", ScreenshotUrl);
            writer.WriteDateTimeOffsetValue("updated", Updated);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Klaviyo.Models.ButtonBlock"/>, <see cref="global::Klaviyo.Models.DropShadowBlock"/>, <see cref="global::Klaviyo.Models.HeaderBlock"/>, <see cref="global::Klaviyo.Models.HorizontalRuleBlock"/>, <see cref="global::Klaviyo.Models.HTMLBlock"/>, <see cref="global::Klaviyo.Models.ImageBlock"/>, <see cref="global::Klaviyo.Models.ProductBlock"/>, <see cref="global::Klaviyo.Models.ReviewBlock"/>, <see cref="global::Klaviyo.Models.Section"/>, <see cref="global::Klaviyo.Models.SocialBlock"/>, <see cref="global::Klaviyo.Models.SpacerBlock"/>, <see cref="global::Klaviyo.Models.SplitBlock"/>, <see cref="global::Klaviyo.Models.TableBlock"/>, <see cref="global::Klaviyo.Models.TextBlock"/>, <see cref="global::Klaviyo.Models.UnsupportedBlock"/>, <see cref="global::Klaviyo.Models.VideoBlock"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PatchUniversalContentResponse_data_attributes_definition : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.ButtonBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.ButtonBlock? ButtonBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.ButtonBlock ButtonBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.DropShadowBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.DropShadowBlock? DropShadowBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.DropShadowBlock DropShadowBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.HeaderBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.HeaderBlock? HeaderBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.HeaderBlock HeaderBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.HorizontalRuleBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.HorizontalRuleBlock? HorizontalRuleBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.HorizontalRuleBlock HorizontalRuleBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.HTMLBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.HTMLBlock? HTMLBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.HTMLBlock HTMLBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.ImageBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.ImageBlock? ImageBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.ImageBlock ImageBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.ProductBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.ProductBlock? ProductBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.ProductBlock ProductBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.ReviewBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.ReviewBlock? ReviewBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.ReviewBlock ReviewBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.Section"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.Section? Section { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.Section Section { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.SocialBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.SocialBlock? SocialBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.SocialBlock SocialBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.SpacerBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.SpacerBlock? SpacerBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.SpacerBlock SpacerBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.SplitBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.SplitBlock? SplitBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.SplitBlock SplitBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.TableBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.TableBlock? TableBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.TableBlock TableBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.TextBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.TextBlock? TextBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.TextBlock TextBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.UnsupportedBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.UnsupportedBlock? UnsupportedBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.UnsupportedBlock UnsupportedBlock { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.VideoBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.VideoBlock? VideoBlock { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.VideoBlock VideoBlock { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Klaviyo.Models.PatchUniversalContentResponse_data_attributes.PatchUniversalContentResponse_data_attributes_definition();
                if("ButtonBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ButtonBlock = new global::Klaviyo.Models.ButtonBlock();
                }
                else if("DropShadowBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.DropShadowBlock = new global::Klaviyo.Models.DropShadowBlock();
                }
                else if("HTMLBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.HTMLBlock = new global::Klaviyo.Models.HTMLBlock();
                }
                else if("HeaderBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.HeaderBlock = new global::Klaviyo.Models.HeaderBlock();
                }
                else if("HorizontalRuleBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.HorizontalRuleBlock = new global::Klaviyo.Models.HorizontalRuleBlock();
                }
                else if("ImageBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ImageBlock = new global::Klaviyo.Models.ImageBlock();
                }
                else if("ProductBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProductBlock = new global::Klaviyo.Models.ProductBlock();
                }
                else if("ReviewBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ReviewBlock = new global::Klaviyo.Models.ReviewBlock();
                }
                else if("Section".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Section = new global::Klaviyo.Models.Section();
                }
                else if("SocialBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.SocialBlock = new global::Klaviyo.Models.SocialBlock();
                }
                else if("SpacerBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.SpacerBlock = new global::Klaviyo.Models.SpacerBlock();
                }
                else if("SplitBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.SplitBlock = new global::Klaviyo.Models.SplitBlock();
                }
                else if("TableBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TableBlock = new global::Klaviyo.Models.TableBlock();
                }
                else if("TextBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TextBlock = new global::Klaviyo.Models.TextBlock();
                }
                else if("UnsupportedBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnsupportedBlock = new global::Klaviyo.Models.UnsupportedBlock();
                }
                else if("VideoBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.VideoBlock = new global::Klaviyo.Models.VideoBlock();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ButtonBlock != null)
                {
                    return ButtonBlock.GetFieldDeserializers();
                }
                else if(DropShadowBlock != null)
                {
                    return DropShadowBlock.GetFieldDeserializers();
                }
                else if(HeaderBlock != null)
                {
                    return HeaderBlock.GetFieldDeserializers();
                }
                else if(HorizontalRuleBlock != null)
                {
                    return HorizontalRuleBlock.GetFieldDeserializers();
                }
                else if(HTMLBlock != null)
                {
                    return HTMLBlock.GetFieldDeserializers();
                }
                else if(ImageBlock != null)
                {
                    return ImageBlock.GetFieldDeserializers();
                }
                else if(ProductBlock != null)
                {
                    return ProductBlock.GetFieldDeserializers();
                }
                else if(ReviewBlock != null)
                {
                    return ReviewBlock.GetFieldDeserializers();
                }
                else if(Section != null)
                {
                    return Section.GetFieldDeserializers();
                }
                else if(SocialBlock != null)
                {
                    return SocialBlock.GetFieldDeserializers();
                }
                else if(SpacerBlock != null)
                {
                    return SpacerBlock.GetFieldDeserializers();
                }
                else if(SplitBlock != null)
                {
                    return SplitBlock.GetFieldDeserializers();
                }
                else if(TableBlock != null)
                {
                    return TableBlock.GetFieldDeserializers();
                }
                else if(TextBlock != null)
                {
                    return TextBlock.GetFieldDeserializers();
                }
                else if(UnsupportedBlock != null)
                {
                    return UnsupportedBlock.GetFieldDeserializers();
                }
                else if(VideoBlock != null)
                {
                    return VideoBlock.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(ButtonBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.ButtonBlock>(null, ButtonBlock);
                }
                else if(DropShadowBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.DropShadowBlock>(null, DropShadowBlock);
                }
                else if(HeaderBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.HeaderBlock>(null, HeaderBlock);
                }
                else if(HorizontalRuleBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.HorizontalRuleBlock>(null, HorizontalRuleBlock);
                }
                else if(HTMLBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.HTMLBlock>(null, HTMLBlock);
                }
                else if(ImageBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.ImageBlock>(null, ImageBlock);
                }
                else if(ProductBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.ProductBlock>(null, ProductBlock);
                }
                else if(ReviewBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.ReviewBlock>(null, ReviewBlock);
                }
                else if(Section != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.Section>(null, Section);
                }
                else if(SocialBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.SocialBlock>(null, SocialBlock);
                }
                else if(SpacerBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.SpacerBlock>(null, SpacerBlock);
                }
                else if(SplitBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.SplitBlock>(null, SplitBlock);
                }
                else if(TableBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.TableBlock>(null, TableBlock);
                }
                else if(TextBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.TextBlock>(null, TextBlock);
                }
                else if(UnsupportedBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.UnsupportedBlock>(null, UnsupportedBlock);
                }
                else if(VideoBlock != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.VideoBlock>(null, VideoBlock);
                }
            }
        }
    }
}
#pragma warning restore CS0618
