// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>The current status of the campaign</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostCampaignResponse_data_attributes_status
    {
        [EnumMember(Value = "Adding Recipients")]
        #pragma warning disable CS1591
        AddingRecipients,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled: Account Disabled")]
        #pragma warning disable CS1591
        CancelledAccountDisabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled: Internal Error")]
        #pragma warning disable CS1591
        CancelledInternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled: No Recipients")]
        #pragma warning disable CS1591
        CancelledNoRecipients,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled: Smart Sending")]
        #pragma warning disable CS1591
        CancelledSmartSending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "Preparing to schedule")]
        #pragma warning disable CS1591
        PreparingToSchedule,
        #pragma warning restore CS1591
        [EnumMember(Value = "Preparing to send")]
        #pragma warning disable CS1591
        PreparingToSend,
        #pragma warning restore CS1591
        [EnumMember(Value = "Queued without Recipients")]
        #pragma warning disable CS1591
        QueuedWithoutRecipients,
        #pragma warning restore CS1591
        [EnumMember(Value = "Scheduled")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sending")]
        #pragma warning disable CS1591
        Sending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sending Segments")]
        #pragma warning disable CS1591
        SendingSegments,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sent")]
        #pragma warning disable CS1591
        Sent,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "Variations Sent")]
        #pragma warning disable CS1591
        VariationsSent,
        #pragma warning restore CS1591
    }
}
