// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>Corresponds to the object which triggered the flow.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostFlowV2Response_data_attributes_trigger_type
    {
        [EnumMember(Value = "Added to List")]
        #pragma warning disable CS1591
        AddedToList,
        #pragma warning restore CS1591
        [EnumMember(Value = "Date Based")]
        #pragma warning disable CS1591
        DateBased,
        #pragma warning restore CS1591
        [EnumMember(Value = "Low Inventory")]
        #pragma warning disable CS1591
        LowInventory,
        #pragma warning restore CS1591
        [EnumMember(Value = "Metric")]
        #pragma warning disable CS1591
        Metric,
        #pragma warning restore CS1591
        [EnumMember(Value = "Price Drop")]
        #pragma warning disable CS1591
        PriceDrop,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unconfigured")]
        #pragma warning disable CS1591
        Unconfigured,
        #pragma warning restore CS1591
    }
}
