// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum ProfileSubscriptionBulkDeleteJobEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "profile-subscription-bulk-delete-job")]
        #pragma warning disable CS1591
        ProfileSubscriptionBulkDeleteJob,
        #pragma warning restore CS1591
    }
}
