// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Dimension for string profile predictive analytics conditions.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum ProfilePredictiveAnalyticsStringCondition_dimension
    {
        [EnumMember(Value = "predicted_gender")]
        #pragma warning disable CS1591
        Predicted_gender,
        #pragma warning restore CS1591
    }
}
