// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProfilePostalCodeDistanceCondition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The country_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>The filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter? Filter { get; set; }
#nullable restore
#else
        public global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter Filter { get; set; }
#endif
        /// <summary>The postal_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Klaviyo.Models.ProfilePostalCodeDistanceEnum? Type { get; set; }
        /// <summary>Units for profile postal code distance conditions.</summary>
        public global::Klaviyo.Models.ProfilePostalCodeDistanceCondition_unit? Unit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Klaviyo.Models.ProfilePostalCodeDistanceCondition"/> and sets the default values.
        /// </summary>
        public ProfilePostalCodeDistanceCondition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Klaviyo.Models.ProfilePostalCodeDistanceCondition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Klaviyo.Models.ProfilePostalCodeDistanceCondition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Klaviyo.Models.ProfilePostalCodeDistanceCondition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "country_code", n => { CountryCode = n.GetStringValue(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter>(global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter.CreateFromDiscriminatorValue); } },
                { "postal_code", n => { PostalCode = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Klaviyo.Models.ProfilePostalCodeDistanceEnum>(); } },
                { "unit", n => { Unit = n.GetEnumValue<global::Klaviyo.Models.ProfilePostalCodeDistanceCondition_unit>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("country_code", CountryCode);
            writer.WriteObjectValue<global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter>("filter", Filter);
            writer.WriteStringValue("postal_code", PostalCode);
            writer.WriteEnumValue<global::Klaviyo.Models.ProfilePostalCodeDistanceEnum>("type", Type);
            writer.WriteEnumValue<global::Klaviyo.Models.ProfilePostalCodeDistanceCondition_unit>("unit", Unit);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Klaviyo.Models.GreaterThanPositiveNumericFilter"/>, <see cref="global::Klaviyo.Models.LessThanPositiveNumericFilter"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProfilePostalCodeDistanceCondition_filter : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.GreaterThanPositiveNumericFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.GreaterThanPositiveNumericFilter? GreaterThanPositiveNumericFilter { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.GreaterThanPositiveNumericFilter GreaterThanPositiveNumericFilter { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Klaviyo.Models.LessThanPositiveNumericFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Klaviyo.Models.LessThanPositiveNumericFilter? LessThanPositiveNumericFilter { get; set; }
#nullable restore
#else
            public global::Klaviyo.Models.LessThanPositiveNumericFilter LessThanPositiveNumericFilter { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Klaviyo.Models.ProfilePostalCodeDistanceCondition.ProfilePostalCodeDistanceCondition_filter();
                if("GreaterThanPositiveNumericFilter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GreaterThanPositiveNumericFilter = new global::Klaviyo.Models.GreaterThanPositiveNumericFilter();
                }
                else if("LessThanPositiveNumericFilter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.LessThanPositiveNumericFilter = new global::Klaviyo.Models.LessThanPositiveNumericFilter();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GreaterThanPositiveNumericFilter != null)
                {
                    return GreaterThanPositiveNumericFilter.GetFieldDeserializers();
                }
                else if(LessThanPositiveNumericFilter != null)
                {
                    return LessThanPositiveNumericFilter.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(GreaterThanPositiveNumericFilter != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.GreaterThanPositiveNumericFilter>(null, GreaterThanPositiveNumericFilter);
                }
                else if(LessThanPositiveNumericFilter != null)
                {
                    writer.WriteObjectValue<global::Klaviyo.Models.LessThanPositiveNumericFilter>(null, LessThanPositiveNumericFilter);
                }
            }
        }
    }
}
#pragma warning restore CS0618
