// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProfilePredictiveAnalyticsEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "profile-predictive-analytics")]
        #pragma warning disable CS1591
        ProfilePredictiveAnalytics,
        #pragma warning restore CS1591
    }
}
