// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Provided_landlineEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "provided_landline")]
        #pragma warning disable CS1591
        Provided_landline,
        #pragma warning restore CS1591
    }
}
