// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Klaviyo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TargetDateActionData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The target_days property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Klaviyo.Models.TargetDateActionData_target_days?>? TargetDays { get; set; }
#nullable restore
#else
        public List<global::Klaviyo.Models.TargetDateActionData_target_days?> TargetDays { get; set; }
#endif
        /// <summary>The target_time property</summary>
        public Time? TargetTime { get; set; }
        /// <summary>The timezone property</summary>
        public global::Klaviyo.Models.TargetDateActionData_timezone? Timezone { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Klaviyo.Models.TargetDateActionData"/> and sets the default values.
        /// </summary>
        public TargetDateActionData()
        {
            AdditionalData = new Dictionary<string, object>();
            Timezone = global::Klaviyo.Models.TargetDateActionData_timezone.Profile;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Klaviyo.Models.TargetDateActionData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Klaviyo.Models.TargetDateActionData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Klaviyo.Models.TargetDateActionData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "target_days", n => { TargetDays = n.GetCollectionOfEnumValues<global::Klaviyo.Models.TargetDateActionData_target_days>()?.AsList(); } },
                { "target_time", n => { TargetTime = n.GetTimeValue(); } },
                { "timezone", n => { Timezone = n.GetEnumValue<global::Klaviyo.Models.TargetDateActionData_timezone>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Klaviyo.Models.TargetDateActionData_target_days>("target_days", TargetDays);
            writer.WriteTimeValue("target_time", TargetTime);
            writer.WriteEnumValue<global::Klaviyo.Models.TargetDateActionData_timezone>("timezone", Timezone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
