// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>Pre-defined key that represents a set timeframe</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum Timeframe_key
    {
        [EnumMember(Value = "last_12_months")]
        #pragma warning disable CS1591
        Last_12_months,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_30_days")]
        #pragma warning disable CS1591
        Last_30_days,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_365_days")]
        #pragma warning disable CS1591
        Last_365_days,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_3_months")]
        #pragma warning disable CS1591
        Last_3_months,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_7_days")]
        #pragma warning disable CS1591
        Last_7_days,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_90_days")]
        #pragma warning disable CS1591
        Last_90_days,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_month")]
        #pragma warning disable CS1591
        Last_month,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_week")]
        #pragma warning disable CS1591
        Last_week,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_year")]
        #pragma warning disable CS1591
        Last_year,
        #pragma warning restore CS1591
        [EnumMember(Value = "this_month")]
        #pragma warning disable CS1591
        This_month,
        #pragma warning restore CS1591
        [EnumMember(Value = "this_week")]
        #pragma warning disable CS1591
        This_week,
        #pragma warning restore CS1591
        [EnumMember(Value = "this_year")]
        #pragma warning disable CS1591
        This_year,
        #pragma warning restore CS1591
        [EnumMember(Value = "today")]
        #pragma warning disable CS1591
        Today,
        #pragma warning restore CS1591
        [EnumMember(Value = "yesterday")]
        #pragma warning disable CS1591
        Yesterday,
        #pragma warning restore CS1591
    }
}
