// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Models
{
    /// <summary>The Consent status to be set as part of the unsubscribe call. Currently supports &quot;UNSUBSCRIBED&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UnsubscriptionParameters_consent
    {
        [EnumMember(Value = "UNSUBSCRIBED")]
        #pragma warning disable CS1591
        UNSUBSCRIBED,
        #pragma warning restore CS1591
    }
}
