// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Api.FlowMessages.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "flow-action")]
        #pragma warning disable CS1591
        FlowAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "template")]
        #pragma warning disable CS1591
        Template,
        #pragma warning restore CS1591
    }
}
