// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.CouponCodes.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "coupon")]
        #pragma warning disable CS1591
        Coupon,
        #pragma warning restore CS1591
    }
}
