// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Api.Profiles.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GetFieldsSegmentQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "definition")]
        #pragma warning disable CS1591
        Definition,
        #pragma warning restore CS1591
        [EnumMember(Value = "definition.condition_groups")]
        #pragma warning disable CS1591
        DefinitionCondition_groups,
        #pragma warning restore CS1591
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_active")]
        #pragma warning disable CS1591
        Is_active,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_processing")]
        #pragma warning disable CS1591
        Is_processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_starred")]
        #pragma warning disable CS1591
        Is_starred,
        #pragma warning restore CS1591
    }
}
