// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Klaviyo.Api.Profiles.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum PatchAdditionalFieldsProfileQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "subscriptions")]
        #pragma warning disable CS1591
        Subscriptions,
        #pragma warning restore CS1591
        [EnumMember(Value = "predictive_analytics")]
        #pragma warning disable CS1591
        Predictive_analytics,
        #pragma warning restore CS1591
    }
}
